# Generated by Django 2.1.7 on 2022-04-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_auto_20220403_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='processId',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
    ]
